baseURL: "https://ReplayRLB.com/"
languageCode: "en-us"
title: "Replay.RL.Booster Portal"
theme: davsk-gohugo-theme
themesDir: themes
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: ''
  description: If you want to be the best, get mentored by the best!
  facebook: 'https://www.facebook.com/Replayrlboosting-103983008269939'
  twitter: ''
  instagram: 'https://www.instagram.com/replayrl.boosting/'
  youtube: ''
  twitch: 'https://www.twitch.tv/sway_replay'
  tiktok: 'https://www.tiktok.com/@replayrl.boosting'
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-black
  featured_image: /images/gohugo-default-sample-hero-image.jpg
  recent_posts_number: 2
